---
name: libvirt

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Generate devbox locale
        run: sudo locale-gen C.UTF-8

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Debug test environment
        run: devbox run -- make debug

      - name: Install role requirements
        run: devbox run -- make requirements

      - name: Run molecule tests.
        run: devbox run -- make test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
